/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as AboutImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account/route'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as CoinsIndexImport } from './routes/coins/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as CoinsCoinIdImport } from './routes/coins/$coinId'
import { Route as AccountPasswordImport } from './routes/account/password'
import { Route as AccountLinkAccountImport } from './routes/account/link-account'
import { Route as AccountGeneralImport } from './routes/account/general'
import { Route as PathlessLayoutSignupImport } from './routes/_pathlessLayout/signup'
import { Route as PathlessLayoutSigninImport } from './routes/_pathlessLayout/signin'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AccountRouteRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRouteRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoinsIndexRoute = CoinsIndexImport.update({
  id: '/coins/',
  path: '/coins/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const CoinsCoinIdRoute = CoinsCoinIdImport.update({
  id: '/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRoute,
} as any)

const AccountPasswordRoute = AccountPasswordImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AccountRouteRoute,
} as any)

const AccountLinkAccountRoute = AccountLinkAccountImport.update({
  id: '/link-account',
  path: '/link-account',
  getParentRoute: () => AccountRouteRoute,
} as any)

const AccountGeneralRoute = AccountGeneralImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AccountRouteRoute,
} as any)

const PathlessLayoutSignupRoute = PathlessLayoutSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

const PathlessLayoutSigninRoute = PathlessLayoutSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/signin': {
      id: '/_pathlessLayout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PathlessLayoutSigninImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/_pathlessLayout/signup': {
      id: '/_pathlessLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PathlessLayoutSignupImport
      parentRoute: typeof PathlessLayoutRouteImport
    }
    '/account/general': {
      id: '/account/general'
      path: '/general'
      fullPath: '/account/general'
      preLoaderRoute: typeof AccountGeneralImport
      parentRoute: typeof AccountRouteImport
    }
    '/account/link-account': {
      id: '/account/link-account'
      path: '/link-account'
      fullPath: '/account/link-account'
      preLoaderRoute: typeof AccountLinkAccountImport
      parentRoute: typeof AccountRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordImport
      parentRoute: typeof AccountRouteImport
    }
    '/coins/$coinId': {
      id: '/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof CoinsCoinIdImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
    '/coins/': {
      id: '/coins/'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutSigninRoute: typeof PathlessLayoutSigninRoute
  PathlessLayoutSignupRoute: typeof PathlessLayoutSignupRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutSigninRoute: PathlessLayoutSigninRoute,
  PathlessLayoutSignupRoute: PathlessLayoutSignupRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface AccountRouteRouteChildren {
  AccountGeneralRoute: typeof AccountGeneralRoute
  AccountLinkAccountRoute: typeof AccountLinkAccountRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountGeneralRoute: AccountGeneralRoute,
  AccountLinkAccountRoute: AccountLinkAccountRoute,
  AccountPasswordRoute: AccountPasswordRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof PathlessLayoutSigninRoute
  '/signup': typeof PathlessLayoutSignupRoute
  '/account/general': typeof AccountGeneralRoute
  '/account/link-account': typeof AccountLinkAccountRoute
  '/account/password': typeof AccountPasswordRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc': typeof CalcIndexRoute
  '/coins': typeof CoinsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof PathlessLayoutSigninRoute
  '/signup': typeof PathlessLayoutSignupRoute
  '/account/general': typeof AccountGeneralRoute
  '/account/link-account': typeof AccountLinkAccountRoute
  '/account/password': typeof AccountPasswordRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc': typeof CalcIndexRoute
  '/coins': typeof CoinsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/_pathlessLayout/signin': typeof PathlessLayoutSigninRoute
  '/_pathlessLayout/signup': typeof PathlessLayoutSignupRoute
  '/account/general': typeof AccountGeneralRoute
  '/account/link-account': typeof AccountLinkAccountRoute
  '/account/password': typeof AccountPasswordRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc/': typeof CalcIndexRoute
  '/coins/': typeof CoinsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/account'
    | '/about'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/account/general'
    | '/account/link-account'
    | '/account/password'
    | '/coins/$coinId'
    | '/calc'
    | '/coins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/account'
    | '/about'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/account/general'
    | '/account/link-account'
    | '/account/password'
    | '/coins/$coinId'
    | '/calc'
    | '/coins'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/account'
    | '/about'
    | '/settings'
    | '/_pathlessLayout/signin'
    | '/_pathlessLayout/signup'
    | '/account/general'
    | '/account/link-account'
    | '/account/password'
    | '/coins/$coinId'
    | '/calc/'
    | '/coins/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRoute
  CoinsCoinIdRoute: typeof CoinsCoinIdRoute
  CalcIndexRoute: typeof CalcIndexRoute
  CoinsIndexRoute: typeof CoinsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRoute,
  CoinsCoinIdRoute: CoinsCoinIdRoute,
  CalcIndexRoute: CalcIndexRoute,
  CoinsIndexRoute: CoinsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pathlessLayout",
        "/account",
        "/about",
        "/settings",
        "/coins/$coinId",
        "/calc/",
        "/coins/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout/route.tsx",
      "children": [
        "/_pathlessLayout/signin",
        "/_pathlessLayout/signup"
      ]
    },
    "/account": {
      "filePath": "account/route.tsx",
      "children": [
        "/account/general",
        "/account/link-account",
        "/account/password"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/_pathlessLayout/signin": {
      "filePath": "_pathlessLayout/signin.tsx",
      "parent": "/_pathlessLayout"
    },
    "/_pathlessLayout/signup": {
      "filePath": "_pathlessLayout/signup.tsx",
      "parent": "/_pathlessLayout"
    },
    "/account/general": {
      "filePath": "account/general.tsx",
      "parent": "/account"
    },
    "/account/link-account": {
      "filePath": "account/link-account.tsx",
      "parent": "/account"
    },
    "/account/password": {
      "filePath": "account/password.tsx",
      "parent": "/account"
    },
    "/coins/$coinId": {
      "filePath": "coins/$coinId.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    },
    "/coins/": {
      "filePath": "coins/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
