/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CoinsIndexImport } from './routes/coins/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as CoinsCoinIdImport } from './routes/coins/$coinId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoinsIndexRoute = CoinsIndexImport.update({
  id: '/coins/',
  path: '/coins/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const CoinsCoinIdRoute = CoinsCoinIdImport.update({
  id: '/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/coins/$coinId': {
      id: '/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof CoinsCoinIdImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
    '/coins/': {
      id: '/coins/'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc': typeof CalcIndexRoute
  '/coins': typeof CoinsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc': typeof CalcIndexRoute
  '/coins': typeof CoinsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/calc/': typeof CalcIndexRoute
  '/coins/': typeof CoinsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings'
    | '/coins/$coinId'
    | '/calc'
    | '/coins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/settings' | '/coins/$coinId' | '/calc' | '/coins'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/settings'
    | '/coins/$coinId'
    | '/calc/'
    | '/coins/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRoute
  CoinsCoinIdRoute: typeof CoinsCoinIdRoute
  CalcIndexRoute: typeof CalcIndexRoute
  CoinsIndexRoute: typeof CoinsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRoute,
  CoinsCoinIdRoute: CoinsCoinIdRoute,
  CalcIndexRoute: CalcIndexRoute,
  CoinsIndexRoute: CoinsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/settings",
        "/coins/$coinId",
        "/calc/",
        "/coins/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/coins/$coinId": {
      "filePath": "coins/$coinId.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    },
    "/coins/": {
      "filePath": "coins/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
